#!/usr/bin/env ruby
require 'readline'

require_relative 'src/commands'
require_relative 'src/command_parser'
require_relative 'src/network/sockets'
require_relative 'src/user_interface/prompt'
require_relative 'src/user_interface/options'
require_relative 'src/error'
require_relative 'src/network/host_link'
require_relative 'src/network/http'

# Handle user interrupt
trap('INT') { ArcticStrike::Error.quit }

ArcticStrike::Options.program_start

ArcticStrike::Commands.execute("banner")
ArcticStrike::UI.user_prompt()
